//console.log("Hello World".toUpperCase())
//console.log(Math.floor(Math.random()*10))
// console.log(" |   |")
// console.log(" |   |")
// console.log(" |   |")
// console.log("---------")
// console.log(" |   |")
// console.log(" |   |")
// console.log(" |   |")
// console.log("---------")
// console.log(" |   |")
// console.log(" |   |")
// console.log(" |   |")
// let lines = ["   |   |", "   |   |", "   |   |", "------------", "   |   |","   |   |","   |   |", "------------","   |   |","   |   |","   |   |",]
// for(i=0; i< lines.length; i++) { console.log(lines[i])}
